services:
    _defaults:
        autowire: true

    SQLite3:
        class: SQLite3
        arguments:
            $filename: '%env(SQLITE_FILENAME)%'

    Doctrine\Instantiator\Instantiator: ~
    Namlier\TDD\User\Authentication\Application\PasswordHasherInterface:
        class: Namlier\TDD\Common\PasswordHasher
    Namlier\TDD\User\Authentication\Application\PasswordValidatorInterface:
        class: Namlier\TDD\Common\PasswordValidator

    Namlier\TDD\SQL\DB: ~
    Namlier\TDD\User\Authentication\Application\AuthenticationService: ~
    Namlier\TDD\User\Repository\UserRepository: ~
